export interface Job {
    id?: number;  // Optional since it's auto-generated
    client_id: number;
    title: string;
    coverPhoto: string;
    description: string;
    required_skills: string;
    budget: number;
    deadline?: Date;  // Optional as it can be NULL
    status?: 'open' | 'in progress' | 'completed' | 'cancelled';  // Defaults to 'open'
    created_at?: Date;  // Auto-generated by the database
}
