### Create a Conversation
POST http://localhost:3000/api/chat/conversation
Content-Type: application/json

{
    "client_id": 1,
    "freelancer_id": 2
}

########

### Send a Message
POST http://localhost:3000/api/chat/message
Content-Type: application/json

{
    "conversation_id": 1,
    "sender_id": 1,
    "message_text": "Hello, are you available for work?"
}

#######

### Get Messages
GET http://localhost:3000/api/chat/messages/1

#####

### Mark Message as Read
PATCH http://localhost:3000/api/chat/message/read/1
