### Register a New User
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "username": "saml",
    "email": "eb2.56068.21@student.chuka.ac.ke",
    "password": "rootpassword",
    "role": "user"
}

###

### Login a User
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "eb2.56068.21@student.chuka.ac.ke",
    "password": "rootpassword"
}

###

### Get All Users
GET http://localhost:3000/api/auth/users
Content-Type: application/json

###

### Delete a User
DELETE http://localhost:3000/api/auth/users/1
Content-Type: application/json

###

### Update a User
PUT http://localhost:3000/api/auth/users/10
Content-Type: application/json

{
    "username": "mary",
    "email": "mary@gmail.com",
    "role": "user",
    "phonenumber": "86077332",
    "profile_picture": "https://www.shutterstock.com/image-photo/happy-attractive-african-business-leader-600nw-2451794349.jpg",
    "skills":"Quality Assurance, web development ",
    "bio": "Hi, I’m a passionate and results-driven freelancer specializing in web development and UI/UX design.\nWith over 3 years of experience, I help startups and businesses build responsive, high-performing websites and applications. I'm skilled in HTML, CSS, JavaScript, Angular, and Node.js, and I love turning complex problems into elegant solutions.\n\nI’m committed to delivering quality work, meeting deadlines, and exceeding expectations. Let’s build something great together!"
}
#####

### Get Profile by User ID
GET http://localhost:3000/api/auth/profile/14
Content-Type: application/json

################################
### get clients
GET http://localhost:3000/api/auth/clients
Content-Type: application/json

################################

### get users
GET http://localhost:3000/api/auth/freelancers
Content-Type: application/json

################################

### 🔢 Get Total Number of Clients
GET http://localhost:3000/api/auth/total-clients
Content-Type: application/json

###

### 🔢 Get Total Number of Freelancers
GET http://localhost:3000/api/auth/total-freelancers
Content-Type: application/json