### Register a New User
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "username": "saml",
    "email": "eb2.56068.21@student.chuka.ac.ke",
    "password": "rootpassword",
    "role": "user"
}

###

### Login a User
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "eb2.56068.21@student.chuka.ac.ke",
    "password": "rootpassword"
}

###

### Get All Users
GET http://localhost:3000/api/auth/users
Content-Type: application/json

###

### Delete a User
DELETE http://localhost:3000/api/auth/users/5
Content-Type: application/json

###

### Update a User
PUT http://localhost:3000/api/auth/users/2
Content-Type: application/json

{
    "username": "sammy",
    "email": "eb2.56066.21@student.chuka.ac.ke",
    "role": "admin",
    "phonenumber": "869721082",
    "profile_picture": "pic.img",
    "skills":"engineering",
    "bio": "I am the admin with all permissions"
}
#####

### Get Profile by User ID
GET http://localhost:3000/api/auth/profile/11
Content-Type: application/json

################################